const char *hz_simple_fragment_shader_source = \
	"#version 100\n"
	"\n"
	"precision highp float;\n"
	"\n"
	"struct Light {\n"
	"	vec3 position;\n"
	"};\n"
	"\n"
	"uniform Light light;\n"
	"uniform sampler2D tex;\n"
	"\n"
	"varying vec3 _position;\n"
	"varying vec3 _normal;\n"
	"varying vec3 _uv;\n"
	"varying vec3 _vertex;\n"
	"\n"
	"void main()\n"
	"{\n"
	"	vec3 dir = normalize(light.position - _vertex);\n"
	"	float diffuse = max(dot(_normal, dir), 0.0);\n"
	"	float ambient = 0.2;\n"
	"\n"
	"	float lighting = diffuse + ambient;\n"
	"\n"
	"	vec4 color = texture2D(tex, _uv.xy);\n"
	"	if (color.a < 0.1) {\n"
	"		discard;\n"
	"	}\n"
	"\n"
	"	gl_FragColor = vec4(color.xyz * lighting, 1.0);\n"
	"}\n"
;

const char *hz_simple_vertex_shader_source = \
	"#version 100\n"
	"\n"
	"uniform mat4 MVP;\n"
	"uniform mat4 model;\n"
	"\n"
	"attribute vec3 position;\n"
	"attribute vec3 normal;\n"
	"attribute vec3 uv;\n"
	"\n"
	"varying vec3 _position;\n"
	"varying vec3 _normal;\n"
	"varying vec3 _uv;\n"
	"varying vec3 _vertex;\n"
	"\n"
	"void main()\n"
	"{\n"
	"	gl_Position = MVP * vec4(position, 1.0);\n"
	"	_vertex = vec3(model * vec4(position, 1.0));\n"
	"\n"
	"	_normal = normal;\n"
	"	_uv = uv;\n"
	"}\n"
;
