#include <hz/built-in/shaders/simple.h>

#define GLSL_VERSION	"100"

#define expand(x)	#x
#define stringify(x)	expand(x)

const char *hz_simple_fragment_shader_source = \
	"#version " GLSL_VERSION "\n"
	"\n"
	"precision highp float;\n"
	"\n"
	"struct Light {\n"
	"	vec3 position;\n"
	"	float intensity;\n"
	"	float constant;\n"
	"	float linear;\n"
	"	float quadratic;\n"
	"};\n"
	"\n"
	"const int num_lights = " stringify(HZ_SIMPLE_SHADER_NUM_LIGHTS) ";\n"
	"uniform Light lights[num_lights];\n"
	"uniform sampler2D tex;\n"
	"uniform vec3 camera;\n"
	"\n"
	"varying vec3 _position;\n"
	"varying vec3 _normal;\n"
	"varying vec3 _uv;\n"
	"varying vec3 _vertex;\n"
	"\n"
	"float calc_light(Light light, vec3 normal, vec3 vertex)\n"
	"{\n"
	"	/* TODO: move to material parameters */\n"
	"	const float shininess = 4.0;\n"
	"\n"
	"	vec3 light_dir = normalize(light.position - vertex);\n"
	"	vec3 camera_dir = normalize(camera - vertex);\n"
	"	vec3 reflect_dir = reflect(-light_dir, normal);\n"
	"\n"
	"	float light_distance = length(light.position - vertex);\n"
	"	float ambient = 0.2;\n"
	"	float diffuse = max(dot(normal, light_dir), 0.0);\n"
	"	float specular = pow(max(dot(camera_dir, reflect_dir), 0.0), shininess);\n"
	"\n"
	"	/* 0.0001 prevents division by zero for disabled lights */\n"
	"	float attenuation = 1.0 / (0.0001 + light.constant +\n"
	"			light.linear * light_distance +\n"
	"			light.quadratic * (light_distance * light_distance));\n"
	"	return attenuation * light.intensity * (ambient + 0.6 * diffuse + 0.8 * specular);\n"
	"}\n"
	"\n"
	"void main()\n"
	"{\n"
	"	float lighting = 0.0;\n"
	"\n"
	"       for (int i = 0; i < num_lights; i++) {\n"
	"               lighting += calc_light(lights[i], _normal, _vertex);\n"
	"       }\n"
	"\n"
	"	vec4 color = texture2D(tex, _uv.xy);\n"
	"	if (color.a < 0.1) {\n"
	"		discard;\n"
	"	}\n"
	"\n"
	"	gl_FragColor = vec4(color.xyz * lighting, 1.0);\n"
	"}\n"
;

const char *hz_simple_vertex_shader_source = \
	"#version " GLSL_VERSION "\n"
	"\n"
	"uniform mat4 MVP;\n"
	"uniform mat4 model;\n"
	"\n"
	"attribute vec3 position;\n"
	"attribute vec3 normal;\n"
	"attribute vec3 uv;\n"
	"\n"
	"varying vec3 _position;\n"
	"varying vec3 _normal;\n"
	"varying vec3 _uv;\n"
	"varying vec3 _vertex;\n"
	"\n"
	"void main()\n"
	"{\n"
	"	gl_Position = MVP * vec4(position, 1.0);\n"
	"	_vertex = vec3(model * vec4(position, 1.0));\n"
	"	_normal = normalize(vec3(model * vec4(normal, 0.0)));\n"
	"\n"
	"	_uv = uv;\n"
	"}\n"
;
