#include <hz/built-in/shaders/simple.h>

#define GLSL_VERSION	"100"

#define expand(x)	#x
#define stringify(x)	expand(x)

const char *hz_simple_fragment_shader_source = \
	"#version " GLSL_VERSION "\n"
	"\n"
	"precision highp float;\n"
	"\n"
	"struct Light {\n"
	"	vec3 position;\n"
	"	float intensity;\n"
	"	float constant;\n"
	"	float linear;\n"
	"	float quadratic;\n"
	"};\n"
	"\n"
	"const int num_lights = " stringify(HZ_SIMPLE_SHADER_NUM_LIGHTS) ";\n"
	"uniform Light lights[num_lights];\n"
	"uniform sampler2D tex;\n"
	"\n"
	"varying vec3 _position;\n"
	"varying vec3 _normal;\n"
	"varying vec3 _uv;\n"
	"varying vec3 _vertex;\n"
	"\n"
	"float calc_light(Light light, vec3 normal, vec3 vertex)\n"
	"{\n"
	"	vec3 dir = light.position - vertex;\n"
	"	float diffuse = max(dot(normalize(normal), normalize(dir)), 0.0);\n"
	"	float ambient = 0.2;\n"
	"	float distance = length(dir);\n"
	"\n"
	"	/* 0.0001 prevents division by zero for disabled lights */\n"
	"	float attenuation = 1.0f / (0.0001f + light.constant +\n"
	"			light.linear * distance +\n"
	"			light.quadratic * (distance * distance));\n"
	"	return attenuation * light.intensity * (diffuse + ambient);\n"
	"}\n"
	"\n"
	"void main()\n"
	"{\n"
	"	float lighting = 0.0;\n"
	"\n"
	"       for (int i = 0; i < num_lights; i++) {\n"
	"               lighting += calc_light(lights[i], _normal, _vertex);\n"
	"       }\n"
	"\n"
	"	vec4 color = texture2D(tex, _uv.xy);\n"
	"	if (color.a < 0.1) {\n"
	"		discard;\n"
	"	}\n"
	"\n"
	"	gl_FragColor = vec4(color.xyz * lighting, 1.0);\n"
	"}\n"
;

const char *hz_simple_vertex_shader_source = \
	"#version " GLSL_VERSION "\n"
	"\n"
	"uniform mat4 MVP;\n"
	"uniform mat4 model;\n"
	"\n"
	"attribute vec3 position;\n"
	"attribute vec3 normal;\n"
	"attribute vec3 uv;\n"
	"\n"
	"varying vec3 _position;\n"
	"varying vec3 _normal;\n"
	"varying vec3 _uv;\n"
	"varying vec3 _vertex;\n"
	"\n"
	"void main()\n"
	"{\n"
	"	gl_Position = MVP * vec4(position, 1.0);\n"
	"	_vertex = vec3(model * vec4(position, 1.0));\n"
	"	_normal = vec3(model * vec4(normal, 0.0));\n"
	"\n"
	"	_uv = uv;\n"
	"}\n"
;
